baseurl = "https://hannes.hauswedell.net"
languageCode = "en_GB"
title = "Hannes Hauswedell's homepage"
theme = "after-dark"
copyright = "Unless otherwise noted: text is CC-by-sa; inline code is CC0; pictures are GNU GPL"

PygmentsCodeFences = true
pygmentsuseclasses = true
pygmentsoptions = "linenos=inline"

[Params]
    gh_comment_reponame = "h-2/blog-comments"
    fsfe_comment_reponame = "h2/blog-comments"

[Author]
    name = "Hannes Hauswedell"
    twitter = "__h2__"
    mastodon_instance = "mastodon.social"
    mastodon_user = "__h2__"

[[menu.main]]
  name = "[about]"
  weight = 1
  identifier = "about"
  url = "/"

[[menu.main]]
  name = "[blog posts]"
  weight = 3
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "[blog categories]"
  weight = 4
  identifier = "categories"
  url = "/categories/"

[[menu.main]]
  name = "[messenger table]"
  weight = 8
  identifier = "messenger"
  url = "/messenger/"
[[menu.main]]
  name = "[contact]"
  weight = 10
  identifier = "contact"
  url = "/contact/"
